version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux
os: linux
 
# Place artifacts file inside EC2 instance
files:
  - source: /
    destination: /home/ec2-user/server
 
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
 
hooks:
  ApplicationStart:
    - location: app_start.sh
      timeout: 300
      runas: root