version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21
    commands:
      - go mod download
  build:
    commands:
      - go build

artifacts:
  files:
    - '**/*' # Include all files
