name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Clean up EC2 instance
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22
        script: |
          # Stop the running application
          pkill stfc || true

          # Remove all files of the previous project
          rm -rf /home/${{ secrets.AWS_EC2_USER }}/my-go-app || true

          # Create a directory for the new project
          mkdir -p /home/${{ secrets.AWS_EC2_USER }}/my-go-app

    - name: Upload project files to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22
        source: "."
        target: "/home/${{ secrets.AWS_EC2_USER }}/my-go-app"

    - name: Build and run the new application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.AWS_EC2_USER }}/my-go-app
          go build -o stfc .
          nohup ./stfc > /dev/null 2>&1 &
          
