name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build the Go app
      run: go build -o stfc .

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        port: 22
        script: |
          # Stop the running application
          pkill stfc || true

          # Remove the old binary
          rm /home/${{ secrets.AWS_EC2_USER }}/stfc || true

          # Upload the new binary
          scp -i ${{ secrets.AWS_EC2_SSH_KEY }} stfc ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/stfc

          # Start the new application
          nohup /home/${{ secrets.AWS_EC2_USER }}/stfc > /dev/null 2>&1 &
